// Pontos de fornecimento Petrobras — Diesel S10, Diesel S500 e Gasolina A
// Fonte: Tabelas de Preços Petrobras (precos.petrobras.com.br), preços sem tributos, à vista
// Diesel S10/S500: vigência 01.07.2026 · Gasolina A: vigência 29.05.2026 — preço de tabela, sem descontos de subvenção (MP 1.358/1.363)
const SUPRIMENTO_META = {
  unidade: "R$/m³",
  vigenciaDiesel: "01.07.2026",
  vigenciaGasolina: "29.05.2026",
  fontes: [
    {produto: "Diesel S500 e S10", url: "https://precos.petrobras.com.br/documents/1295200/1296637/Tabelas+de+Pre%C3%A7os+-+Diesel+S500+e+S10+01-07-2026.pdf/2ae654cb-d1e6-1b6e-b307-ca16024c65ae?version=1.0&t=1782911420000"},
    {produto: "Gasolina A", url: "https://precos.petrobras.com.br/documents/1295200/1296640/Tabelas+de+Pre%C3%A7os+-+Gasolina+29-05-26+%284%29.pdf/bf49d328-bff4-3b34-35a6-eb321e879619?version=1.0&t=1781284759000"}
  ]
};
const SUPRIMENTO_POINTS = [
  {id:3000,municipality:'Maceió',state:'AL',lat:-9.6498,lng:-35.7089,prices:[{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4331.5},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2957.5}]},
  {id:3001,municipality:'Itacoatiara',state:'AM',lat:-3.1431,lng:-58.4442,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4405.4},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4405.4},{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4270.4},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4473.2},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4473.2},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4338.2},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3075.8},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3075.8},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2940.8}]},
  {id:3002,municipality:'Fortaleza',state:'CE',lat:-3.7172,lng:-38.5433,prices:[{produto:'Diesel S10',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:4323.1},{produto:'Gasolina A',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:2968.0}]},
  {id:3003,municipality:'Brasília',state:'DF',lat:-15.7939,lng:-47.8828,prices:[{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4540.3},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4543.2},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3164.1},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3167.0}]},
  {id:3004,municipality:'Vila Velha',state:'ES',lat:-20.3297,lng:-40.2925,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4386.3},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4454.6},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:3024.4}]},
  {id:3005,municipality:'Vitória',state:'ES',lat:-20.3155,lng:-40.3128,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4539.2},{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4386.3},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4454.6},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:3024.4}]},
  {id:3006,municipality:'Rio Verde',state:'GO',lat:-17.7975,lng:-50.9264,prices:[{produto:'Diesel S500',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4560.8},{produto:'Diesel S500',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4565.8},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4592.0},{produto:'Diesel S10',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4628.8},{produto:'Diesel S10',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4633.8},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4660.0},{produto:'Gasolina A',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:3257.0},{produto:'Gasolina A',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:3262.0},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3288.2}]},
  {id:3007,municipality:'Senador Canedo',state:'GO',lat:-16.7075,lng:-49.0936,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4463.7},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4479.4},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4531.7},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4547.4},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3159.9},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3175.6},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3170.3}]},
  {id:3008,municipality:'São Luís',state:'MA',lat:-2.5297,lng:-44.3028,prices:[{produto:'Diesel S500',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:4213.0},{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4256.2},{produto:'Diesel S500',modalidade:'LPC',modalidadeDesc:'Livre para Carregamento',preco:4258.0},{produto:'Diesel S500',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4228.0},{produto:'Diesel S10',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:4273.0},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4316.3},{produto:'Diesel S10',modalidade:'LPC',modalidadeDesc:'Livre para Carregamento',preco:4318.1},{produto:'Diesel S10',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4288.1},{produto:'Gasolina A',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:2930.3},{produto:'Gasolina A',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:2945.5}]},
  {id:3009,municipality:'Betim',state:'MG',lat:-19.9678,lng:-44.1983,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4452.5},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4455.2},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4530.0},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4532.7},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3100.6},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3103.3}]},
  {id:3010,municipality:'Uberaba',state:'MG',lat:-19.7482,lng:-47.9319,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4447.3},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4468.2},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4515.8},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4536.7},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3132.5},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3153.4}]},
  {id:3011,municipality:'Uberlândia',state:'MG',lat:-18.9186,lng:-48.2772,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4455.4},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4476.3},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4524.1},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4545.0},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3115.9},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3136.8}]},
  {id:3012,municipality:'Rondonópolis',state:'MT',lat:-16.4706,lng:-54.6356,prices:[{produto:'Diesel S500',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4619.9},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4663.9},{produto:'Diesel S500',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4619.9},{produto:'Diesel S10',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4688.1},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4732.1},{produto:'Diesel S10',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4688.1},{produto:'Gasolina A',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:3297.8},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3341.8},{produto:'Gasolina A',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:3297.8}]},
  {id:3013,municipality:'Sinop',state:'MT',lat:-11.8642,lng:-55.5025,prices:[{produto:'Diesel S500',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4691.5},{produto:'Diesel S500',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4691.5},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4721.5},{produto:'Diesel S10',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:4762.5},{produto:'Diesel S10',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:4762.5},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4792.5},{produto:'Gasolina A',modalidade:'LPD',modalidadeDesc:'Livre para Descarga',preco:3381.0},{produto:'Gasolina A',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:3381.0},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3411.0}]},
  {id:3014,municipality:'Belém',state:'PA',lat:-1.4558,lng:-48.4902,prices:[{produto:'Diesel S500',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:4255.9},{produto:'Diesel S10',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:4328.4},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4381.4},{produto:'Gasolina A',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:2969.7}]},
  {id:3015,municipality:'Santarém',state:'PA',lat:-2.4431,lng:-54.7083,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4370.5},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4486.5},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:3015.0}]},
  {id:3016,municipality:'Vila do Conde',state:'PA',lat:-1.5108,lng:-48.6083,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4244.9},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4317.4},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2958.7}]},
  {id:3017,municipality:'Cabedelo',state:'PB',lat:-6.9811,lng:-34.8339,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4224.8},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2939.1}]},
  {id:3018,municipality:'Ipojuca',state:'PE',lat:-8.4004,lng:-35.0625,prices:[{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4287.4},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4289.3},{produto:'Gasolina A',modalidade:'ETM',modalidadeDesc:'Entrega no Tanque de Destino Marítimo',preco:2947.6},{produto:'Gasolina A',modalidade:'ETD',modalidadeDesc:'Entrega no Tanque de Destino',preco:2957.0}]},
  {id:3019,municipality:'Araucária',state:'PR',lat:-25.5878,lng:-49.4108,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4358.4},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4361.1},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4422.3},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4425.0},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3020.9},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3023.6}]},
  {id:3020,municipality:'Paranaguá',state:'PR',lat:-25.5161,lng:-48.5225,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4296.3},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4306.3},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2904.9}]},
  {id:3021,municipality:'Duque de Caxias',state:'RJ',lat:-22.7858,lng:-43.3117,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4402.0},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4404.7},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4474.5},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4477.2},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3088.9},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3091.6}]},
  {id:3022,municipality:'Volta Redonda',state:'RJ',lat:-22.5202,lng:-44.1042,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4420.6},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3111.5},{produto:'Gasolina A',modalidade:'LPC',modalidadeDesc:'Livre para Carregamento',preco:3123.9}]},
  {id:3023,municipality:'Canoas',state:'RS',lat:-29.9177,lng:-51.1839,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4330.9},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4333.6},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4403.4},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4406.1},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3045.2},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3047.9}]},
  {id:3024,municipality:'Rio Grande',state:'RS',lat:-32.035,lng:-52.0986,prices:[{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4393.6}]},
  {id:3025,municipality:'Biguaçu',state:'SC',lat:-27.4939,lng:-48.6572,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4418.9},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4444.5},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4487.1},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4512.7},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3067.5},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3093.1}]},
  {id:3026,municipality:'Guaramirim',state:'SC',lat:-26.4761,lng:-49.0011,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4403.3},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4428.9},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4471.5},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4497.1},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3050.6},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3076.2}]},
  {id:3027,municipality:'Itajaí',state:'SC',lat:-26.9078,lng:-48.6614,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4418.9},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4444.5},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4487.1},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4512.7},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3067.5},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3093.1}]},
  {id:3028,municipality:'Barueri',state:'SP',lat:-23.509,lng:-46.8761,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4358.3},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4360.3},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4430.8},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4432.8},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3049.8},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3051.8}]},
  {id:3029,municipality:'Cubatão',state:'SP',lat:-23.8953,lng:-46.4253,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4337.1},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4339.8},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4395.2},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4397.9},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:2982.3},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:2985.0}]},
  {id:3030,municipality:'Guarulhos',state:'SP',lat:-23.4543,lng:-46.5337,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4367.0},{produto:'Diesel S500',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4389.6},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4439.5},{produto:'Diesel S10',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:4462.1},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3043.7},{produto:'Gasolina A',modalidade:'LCT',modalidadeDesc:'Livre no Compartimento de Carga do Veículo Recebedor',preco:3066.3}]},
  {id:3031,municipality:'Paulínia',state:'SP',lat:-22.7614,lng:-47.1542,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4382.9},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4385.6},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4451.1},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4453.8},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3060.8},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3063.5}]},
  {id:3032,municipality:'Ribeirão Preto',state:'SP',lat:-21.1775,lng:-47.8103,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4413.2},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4481.7},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3098.4},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3105.6}]},
  {id:3033,municipality:'Santos',state:'SP',lat:-23.9608,lng:-46.3339,prices:[{produto:'Diesel S500',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4272.0},{produto:'Diesel S10',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:4339.8},{produto:'Gasolina A',modalidade:'LTM',modalidadeDesc:'Livre no Terminal Marítimo',preco:2941.9}]},
  {id:3034,municipality:'São Caetano do Sul',state:'SP',lat:-23.6229,lng:-46.5546,prices:[{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4420.2},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4426.9},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3022.7},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3029.4}]},
  {id:3035,municipality:'São José dos Campos',state:'SP',lat:-23.1896,lng:-45.8841,prices:[{produto:'Diesel S500',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4369.4},{produto:'Diesel S500',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4372.1},{produto:'Diesel S10',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:4441.9},{produto:'Diesel S10',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:4444.6},{produto:'Gasolina A',modalidade:'EXA',modalidadeDesc:'Ex-Ponto "A"',preco:3018.1},{produto:'Gasolina A',modalidade:'LPA',modalidadeDesc:'Livre para o Armazém',preco:3020.8}]},
];
