// Terminais de combustíveis — fonte: ANP (Dados Abertos)
// Gerado automaticamente a partir da planilha ANP Dados - Bases e Terminais.xlsx
const TERMINALS = [
  {id:2000,name:'ORIGEM ENERGIA INFRAESTRUTURA PORTUÁRIA S.A.',municipality:'MACEIO',state:'AL',terminalType:'MARÍTIMO',tankCount:7,capacity:'42 mil m³'},
  {id:2001,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'COARI',state:'AM',terminalType:'FLUVIAL',tankCount:1,capacity:'0 mil m³'},
  {id:2002,name:'Terminais Fluviais do Brasil S/A',municipality:'ITACOATIARA',state:'AM',terminalType:'FLUVIAL',tankCount:18,capacity:'106 mil m³'},
  {id:2003,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'CANDEIAS',state:'BA',terminalType:'TERRESTRE',tankCount:12,capacity:'36 mil m³'},
  {id:2004,name:'ULTRACARGO LOGÍSTICA S/A',municipality:'CANDEIAS',state:'BA',terminalType:'MARÍTIMO',tankCount:89,capacity:'209 mil m³'},
  {id:2005,name:'VOPAK BRASIL S/A',municipality:'CANDEIAS',state:'BA',terminalType:'MARÍTIMO',tankCount:58,capacity:'86 mil m³'},
  {id:2006,name:'SIDEL TERMINAIS E ARMAZENAGENS LTDA',municipality:'FEIRA DE SANTANA',state:'BA',terminalType:'TERRESTRE',tankCount:9,capacity:'12 mil m³'},
  {id:2007,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'ITABUNA',state:'BA',terminalType:'TERRESTRE',tankCount:11,capacity:'24 mil m³'},
  {id:2008,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'JEQUIE',state:'BA',terminalType:'TERRESTRE',tankCount:13,capacity:'23 mil m³'},
  {id:2009,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'MADRE DE DEUS',state:'BA',terminalType:'MARÍTIMO',tankCount:40,capacity:'639 mil m³'},
  {id:2010,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'BRASILIA',state:'DF',terminalType:'TERRESTRE',tankCount:7,capacity:'72 mil m³'},
  {id:2011,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'ARACRUZ',state:'ES',terminalType:'MARÍTIMO',tankCount:3,capacity:'61 mil m³'},
  {id:2012,name:'COMPANHIA PORTUÁRIA VILA VELHA - CPVV',municipality:'VILA VELHA',state:'ES',terminalType:'MARÍTIMO',tankCount:3,capacity:'2 mil m³'},
  {id:2013,name:'HIPER PETRO TERMINAL MARÍTIMO LTDA',municipality:'VILA VELHA',state:'ES',terminalType:'MARÍTIMO',tankCount:2,capacity:'3 mil m³'},
  {id:2014,name:'OTAMERICA TERMINAIS LTDA',municipality:'VILA VELHA',state:'ES',terminalType:'MARÍTIMO',tankCount:23,capacity:'70 mil m³'},
  {id:2015,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'VITORIA',state:'ES',terminalType:'MARÍTIMO',tankCount:2,capacity:'11 mil m³'},
  {id:2016,name:'DINÂMICA TERMINAIS RIO VERDE S/A',municipality:'RIO VERDE',state:'GO',terminalType:'TERRESTRE',tankCount:16,capacity:'56 mil m³'},
  {id:2017,name:'DINÂMICA TERMINAIS CANEDO S/A',municipality:'SENADOR CANEDO',state:'GO',terminalType:'TERRESTRE',tankCount:15,capacity:'33 mil m³'},
  {id:2018,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'SENADOR CANEDO',state:'GO',terminalType:'TERRESTRE',tankCount:7,capacity:'122 mil m³'},
  {id:2019,name:'GRANEL QUÍMICA LTDA.',municipality:'SAO LUIS',state:'MA',terminalType:'MARÍTIMO',tankCount:55,capacity:'149 mil m³'},
  {id:2020,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'SAO LUIS',state:'MA',terminalType:'MARÍTIMO',tankCount:7,capacity:'71 mil m³'},
  {id:2021,name:'SANTOS BRASIL PARTICIPAÇÕES S/A',municipality:'SAO LUIS',state:'MA',terminalType:'FLUVIAL',tankCount:4,capacity:'15 mil m³'},
  {id:2022,name:'SANTOS BRASIL PARTICIPAÇÕES S/A',municipality:'SAO LUIS',state:'MA',terminalType:'MARÍTIMO',tankCount:31,capacity:'131 mil m³'},
  {id:2023,name:'TMP TERMINAIS S/A',municipality:'SAO LUIS',state:'MA',terminalType:'MARÍTIMO',tankCount:11,capacity:'0 mil m³'},
  {id:2024,name:'ULTRACARGO LOGÍSTICA S/A',municipality:'SAO LUIS',state:'MA',terminalType:'MARÍTIMO',tankCount:30,capacity:'165 mil m³'},
  {id:2025,name:'LOGUM LOGÍSTICA S.A.',municipality:'UBERABA',state:'MG',terminalType:'TERRESTRE',tankCount:4,capacity:'28 mil m³'},
  {id:2026,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'UBERABA',state:'MG',terminalType:'TERRESTRE',tankCount:12,capacity:'55 mil m³'},
  {id:2027,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'UBERLANDIA',state:'MG',terminalType:'TERRESTRE',tankCount:12,capacity:'47 mil m³'},
  {id:2028,name:'CERRADINHO LOGÍSTICA LTDA',municipality:'CHAPADAO DO SUL',state:'MS',terminalType:'TERRESTRE',tankCount:8,capacity:'9 mil m³'},
  {id:2029,name:'GRANEL QUÍMICA LTDA.',municipality:'LADARIO',state:'MS',terminalType:'FLUVIAL',tankCount:6,capacity:'8 mil m³'},
  {id:2030,name:'TECIAP - TERMINAIS E ARMAZENS GERAIS LTDA',municipality:'RONDONOPOLIS',state:'MT',terminalType:'TERRESTRE',tankCount:15,capacity:'68 mil m³'},
  {id:2031,name:'TEQUIMAR VILA DO CONDE LOGISTICA PORTUARIA S.A.',municipality:'RONDONOPOLIS',state:'MT',terminalType:'TERRESTRE',tankCount:12,capacity:'35 mil m³'},
  {id:2032,name:'ADMINISTRADORA DE BENS E INFRAESTRUTURA LTDA',municipality:'SINOP',state:'MT',terminalType:'TERRESTRE',tankCount:6,capacity:'3 mil m³'},
  {id:2033,name:'TEQUIMAR VILA DO CONDE LOGISTICA PORTUARIA S.A.',municipality:'BARCARENA',state:'PA',terminalType:'MARÍTIMO',tankCount:18,capacity:'123 mil m³'},
  {id:2034,name:'LATITUDE LOGISTICA PORTUARIA S.A.',municipality:'BELEM',state:'PA',terminalType:'MARÍTIMO',tankCount:13,capacity:'42 mil m³'},
  {id:2035,name:'TRANSPETRO BEL 09 S.A.',municipality:'BELEM',state:'PA',terminalType:'FLUVIAL',tankCount:4,capacity:'39 mil m³'},
  {id:2036,name:'ADMINISTRADORA DE BENS E INFRAESTRUTURA LTDA',municipality:'ITAITUBA',state:'PA',terminalType:'FLUVIAL',tankCount:8,capacity:'4 mil m³'},
  {id:2037,name:'ADMINISTRADORA DE BENS E INFRAESTRUTURA LTDA',municipality:'SANTAREM',state:'PA',terminalType:'FLUVIAL',tankCount:8,capacity:'13 mil m³'},
  {id:2038,name:'POSTO DADO ITAITUBA LTDA',municipality:'VITORIA DO XINGU',state:'PA',terminalType:'FLUVIAL',tankCount:4,capacity:'3 mil m³'},
  {id:2039,name:'NORDESTE LOGISTICA I S.A.',municipality:'CABEDELO',state:'PB',terminalType:'MARÍTIMO',tankCount:6,capacity:'22 mil m³'},
  {id:2040,name:'NORDESTE LOGISTICA II S.A.',municipality:'CABEDELO',state:'PB',terminalType:'MARÍTIMO',tankCount:4,capacity:'11 mil m³'},
  {id:2041,name:'NORDESTE LOGISTICA III S.A.',municipality:'CABEDELO',state:'PB',terminalType:'MARÍTIMO',tankCount:6,capacity:'13 mil m³'},
  {id:2042,name:'TECAB - TERMINAIS DE ARMAZENAGENS DE CABEDELO LTDA',municipality:'CABEDELO',state:'PB',terminalType:'MARÍTIMO',tankCount:12,capacity:'51 mil m³'},
  {id:2043,name:'DECAL BRASIL LTDA',municipality:'IPOJUCA',state:'PE',terminalType:'MARÍTIMO',tankCount:13,capacity:'156 mil m³'},
  {id:2044,name:'PANDENOR IMPORTAÇÃO E EXPORTAÇÃO LTDA',municipality:'IPOJUCA',state:'PE',terminalType:'MARÍTIMO',tankCount:32,capacity:'121 mil m³'},
  {id:2045,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'IPOJUCA',state:'PE',terminalType:'MARÍTIMO',tankCount:12,capacity:'93 mil m³'},
  {id:2046,name:'TMP TERMINAIS S/A',municipality:'IPOJUCA',state:'PE',terminalType:'MARÍTIMO',tankCount:17,capacity:'56 mil m³'},
  {id:2047,name:'ULTRACARGO LOGÍSTICA S/A',municipality:'IPOJUCA',state:'PE',terminalType:'MARÍTIMO',tankCount:34,capacity:'126 mil m³'},
  {id:2048,name:'GRANEL QUÍMICA LTDA.',municipality:'TERESINA',state:'PI',terminalType:'TERRESTRE',tankCount:6,capacity:'8 mil m³'},
  {id:2049,name:'NOVA ARAUCARIA LOGISTICA E ARMAZENS LTDA.',municipality:'ARAUCARIA',state:'PR',terminalType:'TERRESTRE',tankCount:8,capacity:'7 mil m³'},
  {id:2050,name:'NACIONAL ARMAZENS DE LIQUIDOS LTDA',municipality:'LONDRINA',state:'PR',terminalType:'TERRESTRE',tankCount:4,capacity:'1 mil m³'},
  {id:2051,name:'USINA DE ACUCAR SANTA TEREZINHA LTDA EM RECUPERACAO JUDICIAL',municipality:'MARINGA',state:'PR',terminalType:'TERRESTRE',tankCount:2,capacity:'3 mil m³'},
  {id:2052,name:'Álcool do Paraná Terminal Portuário S.A.',municipality:'PARANAGUA',state:'PR',terminalType:'MARÍTIMO',tankCount:8,capacity:'39 mil m³'},
  {id:2053,name:'CATTALINI TERMINAIS MARITIMOS S.A.',municipality:'PARANAGUA',state:'PR',terminalType:'MARÍTIMO',tankCount:101,capacity:'526 mil m³'},
  {id:2054,name:'CBL - COMPANHIA BRASILEIRA DE LOGISTICA S/A',municipality:'PARANAGUA',state:'PR',terminalType:'MARÍTIMO',tankCount:30,capacity:'163 mil m³'},
  {id:2055,name:'CPA TERMINAL PARANAGUÁ',municipality:'PARANAGUA',state:'PR',terminalType:'MARÍTIMO',tankCount:34,capacity:'200 mil m³'},
  {id:2056,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'PARANAGUA',state:'PR',terminalType:'MARÍTIMO',tankCount:24,capacity:'167 mil m³'},
  {id:2057,name:'CPA ARMAZÉNS GERAIS LTDA',municipality:'SARANDI',state:'PR',terminalType:'TERRESTRE',tankCount:17,capacity:'91 mil m³'},
  {id:2058,name:'DINORP - DISTRIBUICAO E ABASTECIMENTO NOROESTE DO PARANA LTDA',municipality:'UMUARAMA',state:'PR',terminalType:'TERRESTRE',tankCount:7,capacity:'3 mil m³'},
  {id:2059,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'ANGRA DOS REIS',state:'RJ',terminalType:'MARÍTIMO',tankCount:9,capacity:'142 mil m³'},
  {id:2060,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'DUQUE DE CAXIAS',state:'RJ',terminalType:'TERRESTRE',tankCount:2,capacity:'52 mil m³'},
  {id:2061,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'JAPERI',state:'RJ',terminalType:'TERRESTRE',tankCount:7,capacity:'39 mil m³'},
  {id:2062,name:'COSAN LUBRIFICANTES E ESPECIALIDADES S.A.',municipality:'RIO DE JANEIRO',state:'RJ',terminalType:'MARÍTIMO',tankCount:8,capacity:'17 mil m³'},
  {id:2063,name:'ILHA TERMINAL DISTRIBUIÇÃO DE PRODUTOS DERIVADOS DE PETRÓLEO LTDA.',municipality:'RIO DE JANEIRO',state:'RJ',terminalType:'MARÍTIMO',tankCount:36,capacity:'61 mil m³'},
  {id:2064,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'RIO DE JANEIRO',state:'RJ',terminalType:'MARÍTIMO',tankCount:18,capacity:'165 mil m³'},
  {id:2065,name:'ULTRACARGO LOGÍSTICA S/A',municipality:'RIO DE JANEIRO',state:'RJ',terminalType:'MARÍTIMO',tankCount:24,capacity:'17 mil m³'},
  {id:2066,name:'BRASIL PORT LOGISTICA OFFSHORE E ESTALEIRO NAVAL LTDA',municipality:'SAO JOAO DA BARRA',state:'RJ',terminalType:'MARÍTIMO',tankCount:16,capacity:'76 mil m³'},
  {id:2067,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'VOLTA REDONDA',state:'RJ',terminalType:'TERRESTRE',tankCount:5,capacity:'25 mil m³'},
  {id:2068,name:'3R OPERAÇÕES MARÍTIMAS S.A.',municipality:'GUAMARE',state:'RN',terminalType:'MARÍTIMO',tankCount:11,capacity:'92 mil m³'},
  {id:2069,name:'NORDESTE LOGÍSTICA LTDA.',municipality:'GUAMARE',state:'RN',terminalType:'TERRESTRE',tankCount:7,capacity:'6 mil m³'},
  {id:2070,name:'ADMINISTRADORA DE BENS E INFRAESTRUTURA LTDA',municipality:'PORTO VELHO',state:'RO',terminalType:'FLUVIAL',tankCount:12,capacity:'16 mil m³'},
  {id:2071,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'CANOAS',state:'RS',terminalType:'LACUSTRE',tankCount:6,capacity:'27 mil m³'},
  {id:2072,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'OSORIO',state:'RS',terminalType:'MARÍTIMO',tankCount:12,capacity:'364 mil m³'},
  {id:2073,name:'BRASKEM S/A',municipality:'RIO GRANDE',state:'RS',terminalType:'MARÍTIMO',tankCount:10,capacity:'41 mil m³'},
  {id:2074,name:'GRANEL QUÍMICA LTDA.',municipality:'RIO GRANDE',state:'RS',terminalType:'MARÍTIMO',tankCount:35,capacity:'73 mil m³'},
  {id:2075,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'RIO GRANDE',state:'RS',terminalType:'LACUSTRE',tankCount:24,capacity:'101 mil m³'},
  {id:2076,name:'REFINARIA DE PETRÓLEO RIOGRANDENSE S.A.',municipality:'RIO GRANDE',state:'RS',terminalType:'TERRESTRE',tankCount:8,capacity:'8 mil m³'},
  {id:2077,name:'BRASKEM S/A',municipality:'TRIUNFO',state:'RS',terminalType:'LACUSTRE',tankCount:2,capacity:'12 mil m³'},
  {id:2078,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'BIGUACU',state:'SC',terminalType:'TERRESTRE',tankCount:10,capacity:'38 mil m³'},
  {id:2079,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'GUARAMIRIM',state:'SC',terminalType:'TERRESTRE',tankCount:9,capacity:'19 mil m³'},
  {id:2080,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'ITAJAI',state:'SC',terminalType:'TERRESTRE',tankCount:11,capacity:'50 mil m³'},
  {id:2081,name:'DELTA TERMINAIS DE ARMAZENAMENTO DE DERIVADOS DE PETROLEO LTDA',municipality:'SOMBRIO',state:'SC',terminalType:'TERRESTRE',tankCount:5,capacity:'3 mil m³'},
  {id:2082,name:'Arais Logística e Serviços',municipality:'ARUJA',state:'SP',terminalType:'TERRESTRE',tankCount:6,capacity:'3 mil m³'},
  {id:2083,name:'ARUJA TERMINAIS EIRELI',municipality:'ARUJA',state:'SP',terminalType:'TERRESTRE',tankCount:6,capacity:'2 mil m³'},
  {id:2084,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'BARUERI',state:'SP',terminalType:'TERRESTRE',tankCount:22,capacity:'200 mil m³'},
  {id:2085,name:'SGP SERVIÇOS AUXILIARES AO TRANSPORTE AÉREO LTDA.',municipality:'BAURU',state:'SP',terminalType:'TERRESTRE',tankCount:8,capacity:'1 mil m³'},
  {id:2086,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'CUBATAO',state:'SP',terminalType:'TERRESTRE',tankCount:13,capacity:'114 mil m³'},
  {id:2087,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'GUARAREMA',state:'SP',terminalType:'TERRESTRE',tankCount:7,capacity:'595 mil m³'},
  {id:2088,name:'LOGUM LOGÍSTICA S.A.',municipality:'GUARULHOS',state:'SP',terminalType:'TERRESTRE',tankCount:3,capacity:'45 mil m³'},
  {id:2089,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'GUARULHOS',state:'SP',terminalType:'TERRESTRE',tankCount:22,capacity:'165 mil m³'},
  {id:2090,name:'T LIQ LOGISTICA E SERVIÇOS LTDA.',municipality:'GUARULHOS',state:'SP',terminalType:'TERRESTRE',tankCount:9,capacity:'18 mil m³'},
  {id:2091,name:'SUDESTE TERMINAIS E ARMAZENS GERAIS LTDA',municipality:'OSASCO',state:'SP',terminalType:'TERRESTRE',tankCount:36,capacity:'4 mil m³'},
  {id:2092,name:'BCAG Brasil China Armazens Gerais S/A',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:7,capacity:'9 mil m³'},
  {id:2093,name:'CROSS TERMINAIS - ARMAZENADORA LTDA',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:6,capacity:'9 mil m³'},
  {id:2094,name:'DAO TERMINAIS DE GRANEIS LIQUIDOS LTDA',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:7,capacity:'9 mil m³'},
  {id:2095,name:'METROPOLITANA ARMAZENAMENTO DE COMBUSTIVEIS LTDA',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:4,capacity:'3 mil m³'},
  {id:2096,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:5,capacity:'171 mil m³'},
  {id:2097,name:'TERMINAL CIAPETRO TAURUS',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:11,capacity:'20 mil m³'},
  {id:2098,name:'TERMINAL DE ARMAZENAGEM DE COMBUSTIVEL LTDA.',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:10,capacity:'30 mil m³'},
  {id:2099,name:'TERMINAL DE COMBUSTIVEIS PAULÍNIA S.A.',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:12,capacity:'214 mil m³'},
  {id:2100,name:'TIF - TERMINAL INTERMODAL FUTURO LTDA.',municipality:'PAULINIA',state:'SP',terminalType:'TERRESTRE',tankCount:5,capacity:'8 mil m³'},
  {id:2101,name:'DELTA TANQUES ARMAZENS GERAIS LTDA.',municipality:'RIBEIRAO PRETO',state:'SP',terminalType:'TERRESTRE',tankCount:15,capacity:'96 mil m³'},
  {id:2102,name:'LOGUM LOGÍSTICA S.A.',municipality:'RIBEIRAO PRETO',state:'SP',terminalType:'TERRESTRE',tankCount:5,capacity:'61 mil m³'},
  {id:2103,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'RIBEIRAO PRETO',state:'SP',terminalType:'TERRESTRE',tankCount:4,capacity:'52 mil m³'},
  {id:2104,name:'TRP ARMAZENADORA LTDA',municipality:'RIO DAS PEDRAS',state:'SP',terminalType:'TERRESTRE',tankCount:6,capacity:'2 mil m³'},
  {id:2105,name:'ADONAI QUÍMICA S/A',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:76,capacity:'110 mil m³'},
  {id:2106,name:'Ageo Leste Terminais e Armazéns Gerais Ltda',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:96,capacity:'94 mil m³'},
  {id:2107,name:'AGEO NORTE TERMINAIS E ARMAZÉNS GERAIS S.A',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:50,capacity:'164 mil m³'},
  {id:2108,name:'AGEO TERMINAIS  ARMAZENS GERAIS LTDA',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:110,capacity:'235 mil m³'},
  {id:2109,name:'GRANEL QUÍMICA LTDA.',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:17,capacity:'52 mil m³'},
  {id:2110,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:16,capacity:'263 mil m³'},
  {id:2111,name:'STOLTHAVEN SANTOS LTDA',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:82,capacity:'127 mil m³'},
  {id:2112,name:'ULTRACARGO LOGÍSTICA S/A',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:158,capacity:'291 mil m³'},
  {id:2113,name:'VOPAK BRASIL S/A',municipality:'SANTOS',state:'SP',terminalType:'MARÍTIMO',tankCount:141,capacity:'297 mil m³'},
  {id:2114,name:'CARBONO QUÍMICA LTDA.',municipality:'SAO BERNARDO DO CAMPO',state:'SP',terminalType:'TERRESTRE',tankCount:26,capacity:'2 mil m³'},
  {id:2115,name:'CAVALINI TERMINAIS E ARMAZENS GERAIS EIRELI',municipality:'SAO BERNARDO DO CAMPO',state:'SP',terminalType:'TERRESTRE',tankCount:7,capacity:'3 mil m³'},
  {id:2116,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'SAO CAETANO DO SUL',state:'SP',terminalType:'TERRESTRE',tankCount:20,capacity:'229 mil m³'},
  {id:2117,name:'DIAMOND - ARMAZÉNS GERAIS SOCIEDADE LIMITADA',municipality:'SAO PAULO',state:'SP',terminalType:'TERRESTRE',tankCount:14,capacity:'1 mil m³'},
  {id:2118,name:'PETROBRAS TRANSPORTE S.A - TRANSPETRO',municipality:'SAO SEBASTIAO',state:'SP',terminalType:'MARÍTIMO',tankCount:21,capacity:'507 mil m³'},
  {id:2119,name:'TEQUIMAR VILA DO CONDE LOGISTICA PORTUARIA S.A.',municipality:'PALMEIRANTE',state:'TO',terminalType:'TERRESTRE',tankCount:13,capacity:'0 mil m³'},
  {id:2120,name:'NORSHIP PARTICIPAÇÕES E REPRESENTAÇÕES COMERCIAIS LTDA.',municipality:'PORTO NACIONAL',state:'TO',terminalType:'TERRESTRE',tankCount:12,capacity:'18 mil m³'},
  {id:2121,name:'CONSÓRCIO PEDRO AFONSO - BUNGE',municipality:'TUPIRAMA',state:'TO',terminalType:'TERRESTRE',tankCount:2,capacity:'4 mil m³'},
];